services:
  django:
    build: .
    #command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/mediafiles
    depends_on:
      - postgres
    env_file:
      - .env
  
  # https://hub.docker.com/_/postgres
  postgres:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  
  nginx:
    image: nginx
    ports:
      - 1180:80
      - 1443:443
    volumes:
      - ./templates:/etc/nginx/templates
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/mediafiles
    depends_on:
      - django
    env_file:
      - .env
    
volumes:
  postgres_data:
  static_volume:
  media_volume: